-- published games catalog used by gallery/home/landing
create table if not exists public.published_games (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  filename text not null unique,
  engine text not null default 'Phaser 3',
  status text not null default 'published',
  emoji text null,
  published_at timestamptz not null default now()
);

alter table public.published_games enable row level security;

create policy "published games readable by all"
on public.published_games
for select
to public
using (status = 'published');

create policy "admin write"
on public.published_games
for all
to authenticated
using (false)
with check (false);
