create table if not exists public.credit_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null default 0,
  reason text not null default 'manual',
  created_at timestamptz not null default now()
);

alter table public.credit_ledger enable row level security;

create policy "own ledger"
on public.credit_ledger
for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.add_credits(p_user uuid, p_amount integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.credit_ledger(user_id, amount, reason)
  values (p_user, p_amount, 'manual');
end;
$$;

grant execute on function public.add_credits(uuid, integer) to authenticated;
